// eslint-disable-next-line import/no-anonymous-default-export
export default {
    STORE_USER : 'STORE_USER',
    TOAST_MESSAGE : 'TOAST_MESSAGE',
    SHOW_LOADER: 'SHOW_LOADER',
    STOP_LOADER : 'STOP_LOADER',
    RESET_USER : 'RESET_USER'
}
const MESSAGE_ACTIONS = {
    ADD_FRIEND : 'ADD_FRIEND',
    ADD_FRIENDS : 'ADD_FRIENDS',
    RESET_FRIENDS : 'RESET_FRIENDS',
    SET_FRIEND_ACTIVE : 'SET_FRIEND_ACTIVE',
    REMOVE_FRIEND: 'REMOVE_FRIEND',
    ADD_MESSAGE : "ADD_MESSAGE"
}
export {MESSAGE_ACTIONS};