export default {
    //OUTGOING EVENTS
    GOT_STATUS : "GOT_STATUS",
    GOT_MESSAGE : "GOT_MESSAGE",
    SENT_MESSAGE : "SENT_MESSAGE",
    TYPED : 'TYPED',

    //INCOMING EVENTS
    OFFLINE : "OFFLINE",
    ONLINE : "ONLINE",
    SEND_MESSAGE : "SEND_MESSAGE",
    TYPE : "TYPE",
    IS_TYPING : "IS_TYPING",
    CONNECTION : "connect",
    DISCONNECT : "disconnect",
    ON_FRIEND_SELECT : 'ON_FRIEND_SELECT'
}