export default {
    //OUTGOING EVENTS
    GOT_STATUS : "GOT_STATUS",
    GOT_MESSAGE : "GOT_MESSAGE",
    SENT_MESSAGE : "SENT_MESSAGE",
    TYPED : 'TYPED',

    //INCOMING EVENTS
    GET_STATUS : "GET_STATUS",
    OFFLINE : "OFFLINE",
    ONLINE : "ONLINE",
    SEND_MESSAGE : "SEND_MESSAGE",
    TYPE : "TYPE",
    IS_TYPING : "IS_TYPING",
    CONNECTION : "CONNECTION",
    DISCONNECT : "DISCONNECT",
    ON_FRIEND_SELECT : 'ON_FRIEND_SELECT'
}