export default {
    GET_STATUS : "GET_STATUS",
    GOT_STATUS : "GOT_STATUS",
    OFFLINE : "OFFLINE",
    ONLINE : "ONLINE",
    SEND_MESSAGE : "SEND_MESSAGE",
    SENT_MESSAGE : "SENT_MESSAGE",
    GOT_MESSAGE : "GOT_MESSAGE",
    TYPE : "TYPE",
    IS_TYPING : "IS_TYPING",
    CONNECTION : "CONNECTION",
    DISCONNECT : "DISCONNECT"
}